# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-starter-template-project'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']  # Adjust the port if your app runs on a different port

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']